#
#spring:
#  profiles:
#    active: nacos
server:
  port: 8060

spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
